version: 2.0
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.0
    steps:
      - checkout
      - run:
          name: "Check Java version"
          command: |
            java -version
      - run:
          name: "Check Lein version"
          command: command -v lein && lein --version
