version: 2.0

orbs:
  rn: react-native-community/react-native@1.2.1

jobs:
  build:
    executor: rn/linux_js
    steps:
      - run:
          name: "Check NPM version"
          command: |
            npm --version; yarn --version
